name: Build DATUM Gateway

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Checkout libbase58
        uses: actions/checkout@v4
        with:
          repository: bitcoin/libbase58
          path: libbase58
      
      - name: Checkout libblkmaker
        uses: actions/checkout@v4
        with:
          repository: bitcoin/libblkmaker
          path: libblkmaker
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libjansson-dev libmicrohttpd-dev libsodium-dev
      
      - name: Build DATUM Gateway
        run: |
          cd build
          cmake ..
          make -j$(nproc)
